### ISSUE TITLE
to

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/GoZen_lite#5]
With the GDExtension part finished it's time to make an actual usable video editor! For this I decided to first work on the lite version as this could be my minimum viable project, this way I can more easily experiment with how I will add certain features such as the effects and timeline.

## TO-DO list
_This list is temporary and may change at any moment!_

- [x] Figure out feature list;
- [x] UI positioning plan;
- [ ] Data saving system (project + settings);
- [ ] Media pool;
- [ ] Timeline;
- [ ] Project view;
- [ ] Effects panel;
- [ ] Basic effects;
- [ ] Rendering menu;
- [ ] Title support;
- [ ] Color support (color frames);
- [ ] Transitions;

## Feature list
- Basic effects:
  - Transform controls;
  - Volume control;
  - Adjustable timings for animations;
- On screen title support;
- ~~Subtitle support;~~
- Basic transitions;
- ~~Move-able UI;~~

**Comment by voylin** [comment]
I will take a small break from programming for a bit to recover my health ^^" So won't get any updates done in the next couple of days
